SELECT E.F_NAME, E.L_NAME, JH.START_DATE, J.JOB_TITLE FROM EMPLOYEES E JOIN JOB_HISTORY JH ON E.EMP_ID = JH.EMPL_ID JOIN JOBS J ON E.JOB_ID = J.JOB_IDENT WHERE E.DEP_ID = 5;

SELECT E.EMP_ID, E.L_NAME, E.DEP_ID, D.DEP_NAME FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP WHERE YEAR(E.B_DATE) < 1980;

SELECT E.F_NAME, E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP AND E.SEX = 'M'

UNION

SELECT E.F_NAME, E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP AND E.SEX = 'M';